### ISSUE TITLE
question tag selection not showing in Speak process

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-ios-digita11y#57]
This used to be working properly so that users could select what prompt they wanted to respond to when making a recording, but now, they respond to what item and nothing else. The server does include both item and question as active UI Groups for Speak, so I'm not sure what is happening here.

This could possibly be a data issue, but I don't understand the logic, so I'm not sure what to try to adjust on that side, but happy to try things.

**Comment by seeReadCode** [comment]
You can try debugging here for the initial filtering of contribute tags:

https://github.com/seeRead/roundware-ios-digita11y/blob/master/Digita11y/ContributeViewModel.swift#L60-L70

And here for the follow up questions:

https://github.com/seeRead/roundware-ios-digita11y/blob/master/Digita11y/ContributeViewModel.swift#L32-L56

Relevant RWData methods are here with more debugging if necessary:
https://github.com/seeRead/roundware-ios-digita11y/blob/master/Digita11y/RWData.swift

**Comment by hburgund** [comment]
I did a bunch of data changes/tests and now have it working as intended with the new content structure. I think this should be good enough for now, but this is definitely not a good long-term situation.

The requirements are that one of the Speak UI Groups has to have `index = 1` and the other UI Groups should follow incrementally in the order they are intended to be displayed. The `item` UI Group will not display (as intended) unless it is assigned `index = 1` in which case things get wacko.

If no UI Group has  `index = 1`, the app crashes and there are currently no guidelines to set things up this specific way, so in the future, we should improve this. Ideally, the app would be significantly more tolerant to different data configurations, but again, no need to worry about this now as I have a working situation for the beta testing.

I will close shortly unless there are further thoughts from @seeReadCode or @sinabahram
